config/routes.rb
# frozen_string_literal: true
require 'sidekiq/web'

Rails.application.routes.draw do
  mount Sidekiq::Web => '/sidekiq'
  resources :companies, only: [:new, :edit, :update, :create]
  resources :positions do
  resources :applicants, only: [:index]
  end
  resources :applicants, only: [:new, :create]
  devise_for :users
  root "home#index"
  get "/vaga/:slug", action: :public_position, controller: :positions, as: :public_position
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/applicant.rb
# frozen_string_literal: true

require 'csv'

class Applicant < ApplicationRecord
  belongs_to :user
  belongs_to :position
  validates :name, :email, :phone, :resume, presence: true
  has_one_attached :resume

  validate :correct_resume_mime_type

  def self.as_csv
    attributes = %w[id name email phone]

    CSV.generate(headers: true) do |csv|
      csv << attributes

      all.each do |applicant|
        csv << attributes.map { |attr| applicant.send(attr) }
      end
    end
  end

  private

  def correct_resume_mime_type
    if resume.attached? && !resume.content_type.in?('application/pdf')
      errors.add(:resume, 'foi enviado com o tipo de documento inválido. Favor, enviar somente PDF.')
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/brazil.rb
class Brazil
    class << self
      def states
        {
          'AC': 'Acre',
          'AL': 'Alagoas',
          'AP': 'Amapá',
          'AM': 'Amazonas',
          'BA': 'Bahia',
          'CE': 'Ceará',
          'DF': 'Distrito Federal',
          'ES': 'Espírito Santo',
          'GO': 'Goiás',
          'MA': 'Maranhão',
          'MT': 'Mato Grosso',
          'MS': 'Mato Grosso do Sul',
          'MG': 'Minas Gerais',
          'PA': 'Pará',
          'PB': 'Paraíba',
          'PR': 'Paraná',
          'PE': 'Pernambuco',
          'PI': 'Piauí',
          'RJ': 'Rio de Janeiro',
          'RN': 'Rio Grande do Norte',
          'RS': 'Rio Grande do Sul',
          'RO': 'Rondônia',
          'RR': 'Roraima',
          'SC': 'Santa Catarina',
          'SP': 'São Paulo',
          'SE': 'Sergipe',
          'TO': 'Tocantins'
        }
      end
    end
  end

app/models/company.rb
class Company < ApplicationRecord
  belongs_to :user
  has_many :positions
  has_one_attached :logo
  validates :name, :url, presence: true

end

app/models/position.rb
class Position < ApplicationRecord
  belongs_to :company
  enum career: [:developer, :business_inteligence, :information_technology, :design, 
                :product, :technology, :other]
  enum contract: [:clt, :pj, :match]
  has_rich_text :description
  validates :name, :career, :contract, :city, :state, :summary, presence: true
  before_save :set_slug

  has_many :applicants
  private

  def set_slug
    self.slug = "#{self.company.name.parameterize}-#{self.name.parameterize}"
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_one :company
end

app/controllers/applicants_controller.rb
# frozen_string_literal: true

class ApplicantsController < ApplicationController
  before_action :set_position, only: [:index]
  def index
    @applicants = @position.applicants
    respond_to do |format|
      format.html
      format.csv { send_data @position.applicants.as_csv }
      format.zip do
        UserMailer.export_resume(current_user.id, @position.id).deliver_later
        flash[:success] = 'Currículos estão sendo gerados neste momento. Verifique seu e-mail daqui alguns minutos.'
        redirect_to action: :index
      end
    end
  end

  def new; end

  def create
    @applicant = current_user.applicants.new(applicant_params)
    @position = Position.find(applicant_params[:position_id])

    respond_to do |format|
      if @applicant.save
        flash[:success] = 'Você aplicou para a vaga com sucesso.'
        format.html { redirect_to public_position_path(@applicant.position.slug) }
        format.js { render 'applicants/success' }
      else
        flash[:error] = 'Houve um erro ao aplicar para a vaga. Tente novamente.'
        format.html { render 'positions/public_position' }
        format.js { render partial: 'applicants/new' }
      end
    end
  end

  private

  def set_position
    begin
      @position = current_user.company.positions.find(params[:position_id])
    rescue
      redirect_to positions_path
    end
  end

  def applicant_params
    params.require(:applicant).permit(:name, :email, :phone, :resume, :position_id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :authenticate_user!
  def new
    if current_user.company
      redirect_to edit_company_path(current_user.company), alert: "Você já possui uma empresa. Edite sua empresa existente."
    else
      @company = current_user.build_company
    end
  end

  def create
    @company = current_user.build_company(company_params)
    if @company.save
      flash[:notice] = 'Sua Empresa foi cadastrada com sucesso!!!'
      redirect_to root_path
    else
      flash[:error] = 'Erro ao cadastrar a empresa.'
      render :new
    end  
  end

  def edit
    @company = current_user.company
  end

  def update
    @company = current_user.company
    if @company.update(company_params)
      flash[:notice] = 'Empresa atualizada com sucesso.'
      redirect_to root_path
    else
      flash[:error] = 'Erro ao atualizar a empresa.'
      render :edit
    end
  end

  private

  def company_params
    params.require(:company).permit(:name, :url, :logo)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/positions_controller.rb
class PositionsController < ApplicationController
  before_action :set_company, :set_i18n_careers, :set_i18n_contracts, except: [:public_position]
  before_action :set_position, only: [:edit, :destroy, :update, :show]

  def index
    @positions = @company.positions
  end

  def new
    @position = @company.positions.new
  end

  def edit
  end

  def show
  end

  def destroy
    @position.destroy!
    respond_to do |format|
      format.html { redirect_to positions_path, notice: "Vaga Excluída com Sucesso." }
      format.json { head :no_content }
    end
  end

  def create
    @position = @company.positions.new(params_position)
    if @position.save
      flash[:success] = 'Vaga cadastrada com sucesso.'
      redirect_to positions_path
    else
      render :new
    end
  end

  def update
    if @position.update(params_position)
      redirect_to positions_path
    else
      render :edit
    end
  end

  def public_position
    @position = Position.find_by(slug: params[:slug])
    @applicant = current_user.applicants.new(position_id: @position.id) if user_signed_in?

    respond_to do |format|
      format.html
      format.js { render partial: 'applicants/new' }
    end
  end

  private

  def set_position
    @position = @company.positions.find(params[:id])
  end

  def params_position
    params.require(:position).permit(:name, :career, :contract, :remote, :publish, :city, :state, :summary, :description)
  end

  def set_company
    redirect_to new_company_path if current_user.company.nil?
    @company = current_user.company
  end

  def set_i18n_careers
    @careers = I18n.t('activerecord.attributes.position.careers')
  end

  def set_i18n_contracts
    @contracts = I18n.t('activerecord.attributes.position.contracts')
  end
end

app/helpers/applicants_helper.rb
module ApplicantsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/positions_helper.rb
module PositionsHelper
    def text_position(position)
      "A empresa #{position.company.name} em #{position.city} está com a vaga de #{position.name}. Veja mais detalhes no nosso mural! #{url_position(position)}"
    end
  
    def url_position(position)
      public_position_url(position.slug)
    end
  
    def career_name(career)
      return "Unknown Career" unless career.present?
      I18n.t('activerecord.attributes.position.careers')[career.to_sym] || "Unknown Career"
    end
    
  
    def contract_name(contract)
      I18n.t('activerecord.attributes.position.contracts')[contract.to_sym]
    end
  
    def modality(position)
      position.remote ? 'Remoto' : 'Presencial'
    end
  end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/applicants/index.html.erb
<h1>Applicants#index</h1>
<p>Find me in app/views/applicants/index.html.erb</p>

app/views/applicants/new.html.erb
<h1>Applicants#new</h1>
<p>Find me in app/views/applicants/new.html.erb</p>

app/views/companies/_form.html.erb
<%= simple_form_for @company do |f| %>
  <div class="row">
    <div class="col-mb-12">
      <%= f.input :name, input_html: { class: 'form-control' } %>
    </div>

    <div class="col-mb-6">
    <%= f.input :url, input_html: { class: 'form-control' } %>
    </div>

    <%= image_tag(url_for(@company.logo), class: 'company-logo') unless @company.new_record? && !@company.logo.nil? %>

  <div class="col-mb-6">
  <%= f.input :logo %>
  </div>

  <div class="col-mb-3 mt-4">
    <%= f.button :submit, "Criar Company", class: 'btn btn-primary' %>
  </div>
  </div>
<% end %>

app/views/companies/edit.html.erb
<div>
  <h1 class="mt-3 text-center">Minha Empresa</h1>
 
  <%= render 'form' %>
</div>

app/views/companies/new.html.erb
<div>
  <h1 class="text-center"> Nova Empresa</h1>
  <%= render 'form' %>
</div>

app/views/home/index.html.erb
 
  <div class="my-3 p-3 bg-body rounded shadow-sm">
    <h6 class="border-bottom pb-2 mb-0">Recent updates</h6>
    <div class="d-flex text-body-secondary pt-3">
      <svg class="bd-placeholder-img flex-shrink-0 me-2 rounded" width="32" height="32" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: 32x32" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="#007bff"/><text x="50%" y="50%" fill="#007bff" dy=".3em">32x32</text></svg>
      <p class="pb-3 mb-0 small lh-sm border-bottom">
        <strong class="d-block text-gray-dark">@username</strong>
        Some representative placeholder content, with some information about this user. Imagine this being some sort of status update, perhaps?
      </p>
    </div>
    <div class="d-flex text-body-secondary pt-3">
      <svg class="bd-placeholder-img flex-shrink-0 me-2 rounded" width="32" height="32" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: 32x32" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="#e83e8c"/><text x="50%" y="50%" fill="#e83e8c" dy=".3em">32x32</text></svg>
      <p class="pb-3 mb-0 small lh-sm border-bottom">
        <strong class="d-block text-gray-dark">@username</strong>
        Some more representative placeholder content, related to this other user. Another status update, perhaps.
      </p>
    </div>
    <div class="d-flex text-body-secondary pt-3">
      <svg class="bd-placeholder-img flex-shrink-0 me-2 rounded" width="32" height="32" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: 32x32" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="#6f42c1"/><text x="50%" y="50%" fill="#6f42c1" dy=".3em">32x32</text></svg>
      <p class="pb-3 mb-0 small lh-sm border-bottom">
        <strong class="d-block text-gray-dark">@username</strong>
        This user also gets some representative placeholder content. Maybe they did something interesting, and you really want to highlight this in the recent updates.
      </p>
    </div>
    <small class="d-block text-end mt-3">
      <a href="#">All updates</a>
    </small>
  </div>

  <div class="my-3 p-3 bg-body rounded shadow-sm">
    <h6 class="border-bottom pb-2 mb-0">Suggestions</h6>
    <div class="d-flex text-body-secondary pt-3">
      <svg class="bd-placeholder-img flex-shrink-0 me-2 rounded" width="32" height="32" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: 32x32" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="#007bff"/><text x="50%" y="50%" fill="#007bff" dy=".3em">32x32</text></svg>
      <div class="pb-3 mb-0 small lh-sm border-bottom w-100">
        <div class="d-flex justify-content-between">
          <strong class="text-gray-dark">Full Name</strong>
          <a href="#">Follow</a>
        </div>
        <span class="d-block">@username</span>
      </div>
    </div>
    <div class="d-flex text-body-secondary pt-3">
      <svg class="bd-placeholder-img flex-shrink-0 me-2 rounded" width="32" height="32" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: 32x32" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="#007bff"/><text x="50%" y="50%" fill="#007bff" dy=".3em">32x32</text></svg>
      <div class="pb-3 mb-0 small lh-sm border-bottom w-100">
        <div class="d-flex justify-content-between">
          <strong class="text-gray-dark">Full Name</strong>
          <a href="#">Follow</a>
        </div>
        <span class="d-block">@username</span>
      </div>
    </div>
    <div class="d-flex text-body-secondary pt-3">
      <svg class="bd-placeholder-img flex-shrink-0 me-2 rounded" width="32" height="32" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: 32x32" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="#007bff"/><text x="50%" y="50%" fill="#007bff" dy=".3em">32x32</text></svg>
      <div class="pb-3 mb-0 small lh-sm border-bottom w-100">
        <div class="d-flex justify-content-between">
          <strong class="text-gray-dark">Full Name</strong>
          <a href="#">Follow</a>
        </div>
        <span class="d-block">@username</span>
      </div>
    </div>
    <small class="d-block text-end mt-3">
      <a href="#">All suggestions</a>
    </small>
  </div>

app/views/layouts/action_text/contents/_content.html.erb
<div class="trix-content">
  <%= yield -%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Motinha Vagas" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
    <%= stylesheet_link_tag "theme", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    
    <%= javascript_include_tag 'application', 'data-turbo-track': 'reload', type: 'module' %>
    <script type="text/javascript" src="https://unpkg.com/trix@2.0.8/dist/trix.umd.min.js"></script>
  </head>

  <body>
    <%= render "shared/topbar" %> 
    <main class="container">
      <%= yield %>
    </main>
  </body>
  <footer class="footer mt-auto">
      <div>
        <p>&copy; <%= Time.now.year  %> - desenvolvido por Dev.Motinha</p>
      </div>
  </footer>
</html>

app/views/layouts/devise.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Motinha Vagas" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
    
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "devise", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", type: "module" %>
    <script type="text/javascript" src="https://unpkg.com/trix@2.0.8/dist/trix.umd.min.js"></script>
  </head>

  <body>
    <div id="logreg-forms">
      <%= render "devise/sessions/logreg-forms" %>
    </div>
    
  </body>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Motinha Vagas" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>

    <%= stylesheet_link_tag "devise", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", type: "module" %>
    <script type="text/javascript" src="https://unpkg.com/trix@2.0.8/dist/trix.umd.min.js"></script>
  </head>

  <body>
  <main id="logreg-forms">
       <%= yield %>

    
  </body>
</html>

app/views/positions/_form.html.erb
<%= simple_form_for @position do |f| %>
  <%= f.input :name %>
  <%= f.input :career, as: :select, collection: @careers, label_method: :second, value_method: :first, include_blank: false, selected: @position.career %>
  <%= f.input :contract, as: :select, collection: @contracts, label_method: :second, value_method: :first, include_blank: false, selected: @position.contract %>
  <%= f.input :remote %>
  <%= f.input :publish %>
  <%= f.input :city %>
  <%= f.input :state, as: :select, collection: Brazil.states, label_method: :second, value_method: :first %>
  
  <div style="position: relative;">
    <%= f.input :summary, maxlength: 360, input_html: { class: 'count-textarea', rows: 4, id: 'summary-input' } %>
    <div id="the-count" style="position: absolute; right: 10px; top: 0; font-size: 0.875rem; color: #6c757d;">
      <span id="current">0</span> / <span id="maximum">360</span>
    </div>
  </div>
  
  <label>Descrição</label>
  <%= f.rich_text_area :description %>
  <%= f.button :submit, class: 'btn btn-primary' %>
<% end %>

<script>
  document.addEventListener('DOMContentLoaded', function() {
    var summaryInput = document.getElementById('summary-input');
    var currentCount = document.getElementById('current');
    var maximumCount = document.getElementById('maximum');

    if (summaryInput && currentCount && maximumCount) {
      summaryInput.addEventListener('input', function() {
        var currentLength = summaryInput.value.length;
        currentCount.textContent = currentLength;
      });

      // Initialize the counter on page load
      var initialLength = summaryInput.value.length;
      currentCount.textContent = initialLength;
    }
  });
</script>

app/views/positions/edit.html.erb
<h1>Editar vaga</h1>
<%= render "form" %>

app/views/positions/index.html.erb
<h2>Minhas vagas</h2>

<table class="table">
  <thead class="thead-dark">
    <tr>
      <th scope="col">Título</th>
      <th scope="col">Carreira</th>
      <th scope="col">Local</th>
      <th scope="col">Tipo de contrato</th>
      <th scope="col">Candidaturas</th>
      <th scope="col">Ações</th>
    </tr>
  </thead>
  <tbody>
    <% @positions.each do |position| %>
      <tr>
        <th scope="row"><%= position.name %></th>
        <td><%= career_name(position.career) %></td>
        <td><%= modality(position) %></td> <!-- aplicar helper -->
        <td><%= contract_name(position.contract || 'default_value') %></td>
        <td>
          <% if position.applicants.size > 0 %>
            <%= link_to "Ver aplicações (#{position.applicants.count})", position_applicants_path(position), class: 'btn btn-warning btn-sm' %>
          <% end %>
        </td>
        <td>
          <div class="dropdown">
            <i class="bi bi-gear "id="dropdownMenuButton" data-bs-toggle="dropdown" aria-expanded="false"></i>
            <i class="bi bi-chevron-down dropdown-toggle-arrow" id="dropdownArrow" data-bs-toggle="dropdown" aria-expanded="false"></i>
            <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton">
              <li><%= link_to 'Editar', edit_position_path(position), class: 'dropdown-item' %></li>
              <li>
                <%= button_to position_path(position), method: :delete, data: { confirm: 'Tem certeza de que deseja remover esta vaga?' }, class: 'dropdown-item' do %>
                  <i></i> Remover
                <% end %>
              </li>
            </ul>
          </div>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/positions/new.html.erb
<h1>Publicar Vaga</h1>
<%= render "form" %>

app/views/positions/show.html.erb
<h1>Positions#show</h1>
<p>Find me in app/views/positions/show.html.erb</p>

app/views/shared/_topbar.html.erb
<nav class="navbar navbar-expand-lg fixed-top navbar-dark bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Mota Vagas</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="<%= root_path %>">Inicio</a>
        </li>
        <li class="nav-item">
           <a class="nav-link active" aria-current="page" href="<%= new_company_path %>">Minha Empresa</a>
        </li>

        <% if user_signed_in? %>
          <li class="nav-item">
            <%= button_to "Sair", destroy_user_session_path, method: :delete, class: "btn btn-outline-light" %>
          </li>
          
          <li class="nav-item">
            <%= button_to "Publicar vaga", new_position_path, method: :get, class: "btn btn-outline-light" %>
          </li>


        <% else %>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Login/Cadastro
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Entrar", new_user_session_path, class: "dropdown-item" %></li>
              <li><%= link_to "Cadastrar", new_user_registration_path, class: "dropdown-item" %></li>
            </ul>
          </li>
        <% end %>
      </ul>
      <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>